### PR TITLE
Add documentation for 7 hooks

### PR DESCRIPTION
**Pull request by koertho**
This PR add documentation for ~~5~~ 7 hooks. It also add an expand tag around the hook registration part as the hook reference is IMHO the typical use case why people open the docs. 

The structure of hook documentation is copied from the contao docs :)

As I'm relative new to isotope, it would be great if someone could read over the descriptions and add missing points, since me and copilot not knowing all depths of isotope :smile_cat:

### CODE REVIEW

**Comment by koertho** [comment]
I added one additional hook and remove the "only in english" notice on the english page.

P.S.: The dev page is hidden in the navigation in the live version of the docs, local it is visible.

**Comment by koertho** [comment]
Mir ist aufgefallen, dass ich als Parmeter teilweise `AbstractProduct` und teilweise `IsotopeProduct` nutze. Das sollten wir eventuell vereinheitlichen. Was wäre die bessere Wahl? Mein erster Instinkt wäre `IsotopeProduct`

**Comment by koertho** [comment]
And one more hook :)

**Review by aschempp — COMMENTED** [review]
Looks good! Just some minor nitpicks 🙃

**Comment by aschempp** [comment]
Thank you @koertho

**Pull request merged**
