### PR TITLE
Changed the Isotope Version

### PR DESCRIPTION
**Pull request by michelbalzer**

### CODE REVIEW

**Comment by michelbalzer** [comment]
Is there a way to automate this a bit?

**Comment by Toflar** [comment]
Hmm, there's not really for every hotfix branch and I also think it's wrong. We follow semantic versioning so if you require `2.*` you will automatically get the latest compatible version of Isotope 2. Why would you ever require explicitly `2.3.3`? I think we should rather teach people to use `2.3.*` for the latest `2.3` release. What do you think?

**Comment by michelbalzer** [comment]
Yeah, I agree with that.

**Comment by Toflar** [comment]
Fixed in https://github.com/isotope/docs/commit/4b983f55ab0aaaea27ca42911c8165e7705c5b20.

**Pull request closed without merging**
